server.port=9090

spring.application.name=stats-server

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/ewm_stats}
spring.datasource.username=${POSTGRES_USER:stats}
spring.datasource.password=${POSTGRES_PASSWORD:stats}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info