services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats